### ISSUE TITLE
First and last keyframe always ignored when compiling keyframes

### ISSUE THREAD

**Issue by djmattyg007** [samisalreadytaken/keyframes#3]
I'm not sure why but it appears the first and last keyframe are always ignored for the purposes of compiling the path. Is this intentional?

**Comment by samisalreadytaken** [comment]
That's just how spline interpolation works. To smoothly interpolate between 3 or more keyframes, each interpolated point calculates values from the keyframes before and after. There are countless resources on the internet if you're curious about the math.

To test the effects of it you can create some keyframes and change the first and last using `kf_select`, `kf_copy` and `kf_replace`; or change the angle roll with `kf_see`.

If you want to duplicate these first and last keyframes, you can `kf_select` > `kf_copy` > `kf_insert` on the first one, and `kf_copy` > `kf_add` for the last one.

**Comment by djmattyg007** [comment]
It might be worth documenting this in the readme.

**Comment by djmattyg007** [comment]
Or perhaps it would be better to automatically insert those dummy keyframes for the user at compile time?

**Comment by samisalreadytaken** [comment]
v1.2.0 adds `kf_auto_fill_boundaries` command for automatically filling boundary key frames on compile (or preview). It is turned off by default, I may or may not change this later.

To make this a persistent setting, you can put `script _KF_.SetAutoFillBoundaries(1)` at the bottom of the `/cfg/keyframes.cfg` file.
