### ISSUE TITLE
Confusion around loading saved data

### ISSUE THREAD

**Issue by djmattyg007** [samisalreadytaken/keyframes#4]
Whenever I use the `kf_load` command it doesn't appear to do anything at all.

Whenever I use the `script kf_load(name_of_data)` command, it does load the data. However, the keyframes don't show up when I turn on edit mode. The path does play back fine though.

**Comment by samisalreadytaken** [comment]
`kf_load` reloads the `keyframes_data.nut` file, `script kf_load()` loads the named data itself. I'll probably rename `kf_load` to `kf_loadfile` to prevent this confusion.

Keyframe and path datas are separate, you'll need to save and load them separately with `kf_save` and `kf_savekeys`.

Unless you're saving the final path for the sole purpose of playing back, I suggest always saving keyframes, as you can always compile keyframe data, but cannot get keyframes from compiled path data.

**Comment by djmattyg007** [comment]
Right. Would it be worth renaming the `kf_save` command to make this more obvious?

**Comment by samisalreadytaken** [comment]
This difference is indicated in the command list, after compile, after save, and after load. How do you think it could be made more clear?

**Comment by djmattyg007** [comment]
Perhaps `kf_savecompiled` would be better?

**Comment by samisalreadytaken** [comment]
Resolved in v1.2.0. `kf_save` is deprecated and `kf_savepath` is added. See the changelog for a list of changes.
