### ISSUE TITLE
Using in live Matches

### ISSUE THREAD

**Issue by AlessandroOrth** [samisalreadytaken/keyframes#5]
Hey man, since I´m Casting I would like to use the camera paths in the live games.
The Problem is the 3 second countdown and the displayed panel for the countdown.
Is there any way to change the countdown and display of the panel?
If there would be an easy command for this I think there wouldn´t be a problem to throw together a .cfg file for me, to use it in a live game.

Thank you in advance for this beautiful project^^

**Comment by samisalreadytaken** [comment]
Sorry for the late reply.

I can make these changes when I get access to a computer, in the meanwhile you can disable these yourself by removing the lines below. If this all works well, I might add the ability to keep multiple paths loaded at once as well.

Though note that I haven’t tested this script for spectators before, and the first player to join the server is chosen as the camera controller.

Hud text

https://github.com/samisalreadytaken/keyframes/blob/ff1b73888b6b364e3596355ded19ff54ef7ec3a0/csgo/scripts/vscripts/keyframes.nut#L403-L404

Sound

https://github.com/samisalreadytaken/keyframes/blob/ff1b73888b6b364e3596355ded19ff54ef7ec3a0/csgo/scripts/vscripts/keyframes.nut#L398

Playback countdown

https://github.com/samisalreadytaken/keyframes/blob/ff1b73888b6b364e3596355ded19ff54ef7ec3a0/csgo/scripts/vscripts/keyframes.nut#L7479-L7498

Auto team assignment

https://github.com/samisalreadytaken/keyframes/blob/ff1b73888b6b364e3596355ded19ff54ef7ec3a0/csgo/scripts/vscripts/keyframes.nut#L7832-L7833

**Comment by samisalreadytaken** [comment]
v1.3.2 adds spectator and multiple path playback support. See the changelog and readme for details. Everything now works in dedicated servers as well, granted `script` command can be executed.
